Test against py35 and py36
Also fix up travis config to to test flake8 and install missing python
versions. Previously some tests passed with:

    ERROR: InterpreterNotFound: python2.6
    SKIPPED:  py26: InterpreterNotFound: python2.6