Handle a blank stat value (#388)
A stat with a blank value makes the .stats() call fail with index error.

```
memcache_connection.stats()
File "/lib/python3.6/site-packages/pymemcache/client/base.py", line 741, in stats
result = self._fetch_cmd(b'stats', args, False)
File "/lib/python3.6/site-packages/pymemcache/client/base.py", line 921, in _fetch_cmd
result[key_value[1]] = key_value[2]
IndexError: list index out of range
```

The line in question we saw that caused this:

```
b'STAT ep_initfile '
```

This fixes things to no longer blow up.   I chose to use a blank binary string instead of None because I suspect other code might make assumptions about the data being binary strings due to this bug.

Co-authored-by: reecepeg <reecepeg@amazon.com>