Add gevent to test-requirements
So when we run integration tests via tox we test gevent integration as
well.

Skip gevent on pypy since travis's pypy version is too old
       Exception: PyPy 2.6.1 or higher is required